#!/usr/bin/env python3
import subprocess
import platform

version = platform.python_version()


if version < "3.5":
	raise Exception("Python 3.5 or a more recent version is required.")


print('Getting all available adapters')
getAdapters = subprocess.run(['networksetup', '-listallnetworkservices'], capture_output=True, text=True)
adapterArray = getAdapters.stdout.split('\n')

# Remove first and last items
del adapterArray[0]
del adapterArray[-1]

print('Turning off ipv6...')
for adapter in adapterArray:
	item = subprocess.run(['networksetup', '-setv6off', adapter], capture_output=True,text=True)
	print(f'Turning off for: {adapter}')

print('All adapters now running ipv4 only')
